version: '3.6'
services:
  psql:
    image: postgres:alpine
    container_name: psql
    ports:
      - 54321:5432
    restart: always
    networks:
      - develop

networks:
  develop:
    name: develop
